// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VelvetIvoryApi.Data;

#nullable disable

namespace VelvetIvoryApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213235702_UpdateProductImages")]
    partial class UpdateProductImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-role-id",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "customer-role-id",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id",
                            RoleId = "admin-role-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VelvetIvoryApi.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74ef0608-4a93-4074-9bc7-fa4ba1bd1821",
                            Email = "admin@velvet.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@VELVET.COM",
                            NormalizedUserName = "ADMIN@VELVET.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKQelat9NjJB/V0nUgTRDaODG0XdmhCEihMElD/XYSe9F2Suff0Kckp32mOA7ljkbQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2669713c-698e-40f8-a45c-1405cc90f2c3",
                            TwoFactorEnabled = false,
                            UserName = "admin@velvet.com"
                        });
                });

            modelBuilder.Entity("VelvetIvoryApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VelvetIvoryApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("VelvetIvoryApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Lingerie",
                            Description = "Luxurious 100% silk kimono robe in champagne gold.",
                            ImageUrl = "https://images.unsplash.com/photo-1627916388484-934c26b4293f?auto=format&fit=crop&q=80&w=800",
                            Name = "Silk Kimono Robe",
                            Price = 129.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            Category = "Wellness",
                            Description = "Organic body oil infused with jasmine and vanilla.",
                            ImageUrl = "https://images.unsplash.com/photo-1615900119312-2acd3a71f3ad?auto=format&fit=crop&q=80&w=800",
                            Name = "Velvet Body Oil",
                            Price = 45.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Category = "Lingerie",
                            Description = "Intricate black lace bralette and panty set.",
                            ImageUrl = "https://images.unsplash.com/photo-1596482163618-20a20275ccca?auto=format&fit=crop&q=80&w=800",
                            Name = "Midnight Lace Set",
                            Price = 85.50m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            Category = "Wellness",
                            Description = "Handcrafted rose quartz wand for facial or body massage.",
                            ImageUrl = "https://images.unsplash.com/photo-1616353329107-742eebe064c5?auto=format&fit=crop&q=80&w=800",
                            Name = "Rose Quartz Massage Wand",
                            Price = 35.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            Category = "Accessories",
                            Description = "Ultra-soft satin sleep mask for deep restorative rest.",
                            ImageUrl = "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&q=80&w=800",
                            Name = "Satin Sleep Mask",
                            Price = 25.00m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            Category = "Wellness",
                            Description = "Soy wax candle with notes of amber and sandalwood.",
                            ImageUrl = "https://images.unsplash.com/photo-1602826673327-1c463138f7bf?auto=format&fit=crop&q=80&w=800",
                            Name = "Golden Ember Candle",
                            Price = 42.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 7,
                            Category = "Accessories",
                            Description = "Elegant soft rope with faux pearl accents for aesthetic play.",
                            ImageUrl = "https://images.unsplash.com/photo-1612450630386-455b79698d28?auto=format&fit=crop&q=80&w=800",
                            Name = "Pearl Bondage Rope",
                            Price = 55.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 8,
                            Category = "Toys",
                            Description = "Glass pleasure wand designed for temperature play.",
                            ImageUrl = "https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?auto=format&fit=crop&q=80&w=800",
                            Name = "Crystal Pleasure Wand",
                            Price = 65.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 9,
                            Category = "Lingerie",
                            Description = "Minimalist sheer bodysuit with velvet piping.",
                            ImageUrl = "https://images.unsplash.com/photo-1583846711818-b6d819ae6e10?auto=format&fit=crop&q=80&w=800",
                            Name = "Sheer Tulle Bodysuit",
                            Price = 95.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 10,
                            Category = "Accessories",
                            Description = "Handheld fan made with ethically sourced ostrich feathers.",
                            ImageUrl = "https://images.unsplash.com/photo-1595181788647-f3d65011684c?auto=format&fit=crop&q=80&w=800",
                            Name = "Ivory Feather Fan",
                            Price = 75.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 11,
                            Category = "Accessories",
                            Description = "Premium leather handcuffs with gold hardware.",
                            ImageUrl = "https://images.unsplash.com/photo-1506152983158-b4a74a01c721?auto=format&fit=crop&q=80&w=800",
                            Name = "Noir Leather Handcuffs",
                            Price = 80.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 12,
                            Category = "Accessories",
                            Description = "Traditional jute rope dyed in deep crimson for bondage art.",
                            ImageUrl = "https://images.unsplash.com/photo-1589363066699-317eb8a24558?auto=format&fit=crop&q=80&w=800",
                            Name = "Crimson Shibari Rope",
                            Price = 40.00m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 13,
                            Category = "Toys",
                            Description = "Luxurious stainless steel plug with a crystal base.",
                            ImageUrl = "https://images.unsplash.com/photo-1615655406736-b37c4fabf923?auto=format&fit=crop&q=80&w=800",
                            Name = "Gold Plated Anal Jewel",
                            Price = 90.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 14,
                            Category = "Toys",
                            Description = "Artisan glass dildo with ergonomic curve for G-spot stimulation.",
                            ImageUrl = "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&q=80&w=800",
                            Name = "Glass Dildo - Curved",
                            Price = 110.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 15,
                            Category = "Accessories",
                            Description = "Pure black silk blindfold to heighten your senses.",
                            ImageUrl = "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&q=80&w=800",
                            Name = "Silk Blindfold",
                            Price = 30.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 16,
                            Category = "Toys",
                            Description = "Discreet vibrating egg with long-range remote control.",
                            ImageUrl = "https://images.unsplash.com/photo-1558553205-d143c7b80a6c?auto=format&fit=crop&q=80&w=800",
                            Name = "Remote Control Egg",
                            Price = 75.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 17,
                            Category = "Lingerie",
                            Description = "Seductive open-cup bra featuring delicate floral lace.",
                            ImageUrl = "https://images.unsplash.com/photo-1549487950-c81b67f185df?auto=format&fit=crop&q=80&w=800",
                            Name = "Lace Open-Cup Bra",
                            Price = 65.00m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 18,
                            Category = "Accessories",
                            Description = "Sophisticated collar with detachable leash for power play.",
                            ImageUrl = "https://images.unsplash.com/photo-1600609842388-3e44917dc9b6?auto=format&fit=crop&q=80&w=800",
                            Name = "Leather Collar & Leash",
                            Price = 95.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 19,
                            Category = "Wellness",
                            Description = "Edible warming oil that heats up with breath.",
                            ImageUrl = "https://images.unsplash.com/photo-1608248597279-f99d160bfbc8?auto=format&fit=crop&q=80&w=800",
                            Name = "Warming Massage Oil",
                            Price = 38.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 20,
                            Category = "Accessories",
                            Description = "Ostrich feather tickler for teasing sensitive zones.",
                            ImageUrl = "https://images.unsplash.com/photo-1595181788647-f3d65011684c?auto=format&fit=crop&q=80&w=800",
                            Name = "Feather Tickler",
                            Price = 28.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 21,
                            Category = "Toys",
                            Description = "Premium silicone vibrator with dual stimulation motors.",
                            ImageUrl = "https://images.unsplash.com/photo-1576426863848-c2185fc6e818?auto=format&fit=crop&q=80&w=800",
                            Name = "Dual Action Rabbit",
                            Price = 140.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 22,
                            Category = "Accessories",
                            Description = "Elegant silicone ball gag with adjustable leather strap.",
                            ImageUrl = "https://images.unsplash.com/photo-1591348276333-113843063e36?auto=format&fit=crop&q=80&w=800",
                            Name = "Noir Gag",
                            Price = 55.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 23,
                            Category = "Toys",
                            Description = "Set of 3 graduated glass plugs for anal exploration.",
                            ImageUrl = "https://images.unsplash.com/photo-1533206485299-52e935496156?auto=format&fit=crop&q=80&w=800",
                            Name = "Glass Butt Plug Set",
                            Price = 90.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 24,
                            Category = "Lingerie",
                            Description = "Full body fishnet stocking for a daring reveal.",
                            ImageUrl = "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=800",
                            Name = "Sheer Bodystocking",
                            Price = 45.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 25,
                            Category = "Accessories",
                            Description = "Adjustable clamps with gold chain connector.",
                            ImageUrl = "https://images.unsplash.com/photo-1621799754526-a0d52c49fad5?auto=format&fit=crop&q=80&w=800",
                            Name = "Gold Nipple Clamps",
                            Price = 32.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 26,
                            Category = "Toys",
                            Description = "Ergonomically designed massager for deep satisfaction.",
                            ImageUrl = "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&q=80&w=800",
                            Name = "Prostate Massager",
                            Price = 85.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 27,
                            Category = "Toys",
                            Description = "The ultimate power in a cordless, rechargeable wand.",
                            ImageUrl = "https://images.unsplash.com/photo-1579453723368-233f2c5d5d83?auto=format&fit=crop&q=80&w=800",
                            Name = "Cordless Magic Wand",
                            Price = 120.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 28,
                            Category = "Accessories",
                            Description = "Firm leather paddle for impact play enthusiasts.",
                            ImageUrl = "https://images.unsplash.com/photo-1600609842388-3e44917dc9b6?auto=format&fit=crop&q=80&w=800",
                            Name = "Leather Spanking Paddle",
                            Price = 50.00m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 29,
                            Category = "Lingerie",
                            Description = "Seductive thong featuring a strand of faux pearls.",
                            ImageUrl = "https://images.unsplash.com/photo-1588117260148-447884962bc5?auto=format&fit=crop&q=80&w=800",
                            Name = "Crotchless Pearl Thong",
                            Price = 35.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 30,
                            Category = "Accessories",
                            Description = "Pinwheel for gentle sensory play and nerve stimulation.",
                            ImageUrl = "https://images.unsplash.com/photo-1632705971485-617d5225c57d?auto=format&fit=crop&q=80&w=800",
                            Name = "Sensation Wheel",
                            Price = 20.00m,
                            Stock = 40
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VelvetIvoryApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VelvetIvoryApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetIvoryApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VelvetIvoryApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VelvetIvoryApi.Models.Order", b =>
                {
                    b.HasOne("VelvetIvoryApi.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VelvetIvoryApi.Models.OrderItem", b =>
                {
                    b.HasOne("VelvetIvoryApi.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetIvoryApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VelvetIvoryApi.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
